services:
  - type: web
    name: koniec-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: koniec-backend.onrender.com
    plan: free

databases:
  - name: koniec-db
    plan: free